### ISSUE TITLE
Assertion error in _liu_pvalue_mod_lambda_zero

### ISSUE THREAD

**Issue by mkerin** [limix/struct-lmm#24]
Hello,

I get the following error sometimes when running StructLMM in simulation, particulary when running StructLMM with large sample sizes. Looking in 

https://github.com/limix/chiscore/blob/master/chiscore/_davies.py

this appears to occur when the p-value is exactly 0 (or atleast gets rounded to 0). I don't suppose you could fix?

```
Traceback (most recent call last):
  File "src/run_struct_lmm.py", line 99, in <module>
    G, bim, pheno, E, covs=covs, batch_size=100, snp_preproc=snp_preproc)
  File "/well/marchini/kebl4230/software/miniconda3/lib/python3.6/site-packages/struct_lmm/lmm/run_structlmm.py", line 121, in run_structlmm
    _p = slmm_int.score_2_dof(x)
  File "/well/marchini/kebl4230/software/miniconda3/lib/python3.6/site-packages/struct_lmm/lmm/structlmm.py", line 227, in score_2_dof
    pval = davies_pvalue(Q_rho[0], LToxPxoL)
  File "/well/marchini/kebl4230/software/miniconda3/lib/python3.6/site-packages/chiscore/_davies.py", line 28, in davies_pvalue
    re = _pvalue_lambda(_lambda(w), q)
  File "/well/marchini/kebl4230/software/miniconda3/lib/python3.6/site-packages/chiscore/_davies.py", line 85, in _pvalue_lambda
    param["d"],
  File "/well/marchini/kebl4230/software/miniconda3/lib/python3.6/site-packages/chiscore/_davies.py", line 156, in _liu_pvalue_mod_lambda_zero
    assert False
AssertionError
```

**Comment by horta** [comment]
Sure we can fix it. Do you have an example for calling `davies_pvalue` from [chiscore](https://github.com/limix/chiscore) package?
