### ISSUE TITLE
Error when running example data on command line

### ISSUE THREAD

**Issue by bergland-rpi** [limix/struct-lmm#6]
Hi, I am excited to give struct-lmm a whirl on my data, but am having issues getting it to work. I downloaded and installed the package and its dependencies according to the instructions and was working my way through the example data from data_structlmm.zip in the command line. The `norm_env  --in $EFILE0 --out $EFILE command ` seems to work fine, but then when I try the `struct_lmm_analyze`  command followed by all the inputs, I get a series of errors ending with "ValueError: The truth value of a Series is ambiguous. "
I have copied the full command line call as well as the errors below and would appreciate any guidance in how to resolve this. Thanks very much. 
*update: I am also encountering this error when running the example data in python directly.

(struct-lmm) [priscilla@bergland-lab hybrid]$ BFILE=data_structlmm/chrom22_subsample20_maf0.10
(struct-lmm) [priscilla@bergland-lab hybrid]$ PFILE=data_structlmm/expr.csv
(struct-lmm) [priscilla@bergland-lab hybrid]$ EFILE0=data_structlmm/env.txt
(struct-lmm) [priscilla@bergland-lab hybrid]$ EFILE=data_structlmm/env_norm.txt
(struct-lmm) [priscilla@bergland-lab hybrid]$ norm_env  --in $EFILE0 --out $EFILE
(struct-lmm) [priscilla@bergland-lab hybrid]$ struct_lmm_analyze \
> --bfile $BFILE \
> --pfile $PFILE \
> --pheno_id gene10 \
> --efile $EFILE \
> --ofile out/results.res \
> --idx_start 0 \
> --idx_end 1000 \
> --batch_size 100 \
> --unique_variants

Traceback (most recent call last):
  File "/home/priscilla/miniconda2/envs/struct-lmm/bin/struct_lmm_analyze", line 11, in <module>
    load_entry_point('struct-lmm==0.0.7', 'console_scripts', 'struct_lmm_analyze')()
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/struct_lmm-0.0.7-py2.7.egg/struct_lmm/scripts/struct_lmm_analyze.py", line 74, in entry_point
    reader.subset_snps(query, inplace=True)
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/limix/data/bed_reader.py", line 168, in subset_snps
    geno, snpinfo = self._query(query)
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/limix/data/bed_reader.py", line 248, in _query
    geno = self._geno[snpinfo.i, :]
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/dask/array/core.py", line 1303, in __getitem__
    index2 = normalize_index(index, self.shape)
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/dask/array/slicing.py", line 775, in normalize_index
    check_index(i, d)
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/dask/array/slicing.py", line 826, in check_index
    elif ind >= dimension:
  File "/home/priscilla/miniconda2/envs/struct-lmm/lib/python2.7/site-packages/pandas/core/generic.py", line 1121, in __nonzero__
    .format(self.__class__.__name__))
ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by awedwards** [comment]
In the _query method of the BedReader class, it looks like after the query is converted to snp index, it is passing a pandas Series (rather than a 1-D numpy array) to index _geno.

I tried the following change and it seemed to work:

In _query method, change:

`geno = self._geno[snpinfo.i, :]`

to:
`geno = self._geno[snpinfo.i.values, :]`

Haven't looked too much at the whole project, so I don't know if this fix makes sense... :)

**Comment by horta** [comment]
Hi. @awedwards is correct. A new limix release is in pip with this fix: https://pypi.python.org/pypi?:action=files&name=limix&version=1.0.14
We are preparing now a release to conda-forge. I will get back here soon!

**Comment by horta** [comment]
Hello @bergland-rpi , limix 1.0.17 is on conda-forge for Linux: https://anaconda.org/conda-forge/limix/files
It will be ready for macOS in a couple of minutes, maximum hours with the fix. Thanks a lot for the feedback!

**Comment by horta** [comment]
it has been fixed for a while. Closing it.
